name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
      docker login -u mahimani --password mahesh123 
      docker build -t mahimani/todo-app-project:v1 .
      docker push mahimani/todo-app-project
